- name: Prepare things
  hosts: digitalocean-1
  vars:
    project_dir: "{{ ansible_env.HOME }}/deployments/scripts/regular_payments"
    logs_dir: "{{ ansible_env.HOME }}/logs/scripts/regular_payments"
  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ project_dir }}"
        - "{{ logs_dir }}"
    - name: Create virtual env
      command:
        cmd: "virtualenv {{ project_dir }}/venv -p python3.11 --download"
        creates: "{{ project_dir }}/venv"
