- name: Prepare things
  hosts: hetzner-1
  vars:
    project_dir: "{{ ansible_env.HOME }}/deployments/scripts/vas3k_whois"
    logs_dir: "{{ ansible_env.HOME }}/logs/scripts/vas3k_whois"
  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ project_dir }}"
        - "{{ logs_dir }}"
    - name: Install openssl 1
      become: true
      shell:
        chdir: /tmp
        cmd: "wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb && dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb"
    - name: Create virtual env
      command:
        cmd: "virtualenv {{ project_dir }}/venv -p python3.11 --download"
        creates: "{{ project_dir }}/venv"
