api_id: api_id
api_hash: api_hash
phone: '+7-123-456-78-90'
database_encryption_key: changekey123
chats:
  - -12345
  - -67890
owner_user_id: 12312312
uptime_url: https://uptime-kuma-addr/api/something
uptime_too_big_url: https://uptime-kuma-addr/api/another
