- name: Deploy
  hosts: hetzner-1
  vars:
    scripts_dir: "{{ ansible_env.HOME }}/deployments/scripts"
    project_dir: "{{ ansible_env.HOME }}/deployments/scripts/vas3k_whois"
    logs_prefix: "{{ ansible_env.HOME }}/logs/vas3k_whois"
  tasks:
    - name: Copy sources
      synchronize:
        src: ./src/
        dest: "{{ project_dir }}/src/"
        delete: yes
    - name: Copy config
      synchronize:
        src: ./config.yml
        dest: "{{ project_dir }}/config.yml"
        delete: yes

    - name: Copy systemd service
      template:
        src: ./vas3k-whois.service
        dest: ~/.config/systemd/user/vas3k-whois.service
        mode: 0644
    - name: Restart service
      systemd:
        name: vas3k-whois
        state: restarted
        daemon_reload: yes
        scope: user
        enabled: true
