- name: Deploy
  hosts: hetzner-1
  vars:
    scripts_dir: "{{ ansible_env.HOME }}/deployments/scripts"
    project_dir: "{{ ansible_env.HOME }}/deployments/scripts/regular_payments"
    logs_prefix: "{{ ansible_env.HOME }}/logs/regular_payments"
  tasks:
    - name: Copy sources
      synchronize:
        src: ./src/
        dest: "{{ project_dir }}/src/"
        delete: yes
    - name: Copy config
      synchronize:
        src: ./config.yml
        dest: "{{ project_dir }}/config.yml"
        delete: yes

    - name: Copy systemd service
      template:
        src: ./regular-payments.service
        dest: ~/.config/systemd/user/regular-payments.service
        mode: 0644
    - name: Restart service
      systemd:
        name: regular-payments
        state: restarted
        daemon_reload: yes
        scope: user
        enabled: true
