[tool.poetry]
name = "expenses"
version = "0.1.0"
description = ""
authors = ["Vyacheslav Syrovatsky <vyacheslav@syrovats.ky>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
